Repository os-migrate/os-migrate, pull requests merged in 2020-04, with the labels that each got.

#151 Move README to collection home
  README.md
  os_migrate/README.md
Labels: documentation, enhancement

#147 OOP sec group rules
  os_migrate/plugins/module_utils/reference.py
  os_migrate/plugins/module_utils/security_group_rule.py
  os_migrate/plugins/modules/export_security_group_rules.py
  os_migrate/plugins/modules/import_security_group_rule.py
  os_migrate/tests/unit/fixtures.py
  os_migrate/tests/unit/test_security_group_rule.py
Labels: enhancement, refactoring

#157 Do not ls, use always current version as latest
  scripts/build.sh
Labels: bug, ci, dev env, tech debt

#158 Check build for docs folder
  .github/workflows/docs-check.yml
  doc/devel/dev-env-setup.md
Labels: bug, ci

#131 Galaxy sanity checks
  .github/workflows/consistency-functional.yml
  Makefile
  os_migrate/galaxy.yml
  os_migrate/plugins/modules/export_network.py
  os_migrate/plugins/modules/export_router.py
  os_migrate/plugins/modules/export_router_interfaces.py
  os_migrate/plugins/modules/export_security_group.py
  os_migrate/plugins/modules/export_security_group_rules.py
  os_migrate/plugins/modules/export_subnet.py
  os_migrate/plugins/modules/import_network.py
  os_migrate/plugins/modules/import_router.py
  os_migrate/plugins/modules/import_router_interface.py
  os_migrate/plugins/modules/import_security_group.py
  os_migrate/plugins/modules/import_security_group_rule.py
  os_migrate/plugins/modules/import_subnet.py
  os_migrate/plugins/modules/os_routers_info.py
  os_migrate/plugins/modules/os_security_group_rules_info.py
  os_migrate/plugins/modules/os_security_groups_info.py
  os_migrate/plugins/modules/read_resources.py
  os_migrate/plugins/modules/validate_resource_files.py
  os_migrate/roles/import_networks/tasks/main.yml
  os_migrate/roles/import_router_interfaces/tasks/main.yml
  os_migrate/roles/import_routers/tasks/main.yml
  os_migrate/roles/import_security_group_rules/tasks/main.yml
  os_migrate/roles/import_security_groups/tasks/main.yml
  os_migrate/roles/import_subnets/tasks/main.yml
  os_migrate/roles/validate_data_dir/tasks/main.yml
  os_migrate/tests/sanity/ignore-2.9.txt
  toolbox/Dockerfile
Labels: ci, enhancement, tech debt

#165 Force upgrade virtualenv
  .github/workflows/consistency-functional.yml
  toolbox/build/build.sh
Labels: blocker, bug, ci, dev env

#166 Router fixes
  os_migrate/playbooks/import_routers.yml
  os_migrate/plugins/module_utils/router.py
Labels: bug

#162 Basic workload information export.
  os_migrate/playbooks/export_workloads.yml
  os_migrate/plugins/module_utils/const.py
  os_migrate/plugins/module_utils/server.py
  os_migrate/plugins/modules/export_workload.py
  os_migrate/roles/export_workloads/defaults/main.yml
  os_migrate/roles/export_workloads/meta/main.yml
  os_migrate/roles/export_workloads/tasks/main.yml
  os_migrate/tests/sanity/ignore-2.9.txt
  os_migrate/tests/unit/test_workload.py
Labels: enhancement

#171 Save ether_type for security group rules
  os_migrate/plugins/module_utils/security_group_rule.py
  os_migrate/tests/unit/test_security_group_rule.py
Labels: bug

#175 Make sure releasing is done from toolbox container
  scripts/publish.sh
Labels: dev env

#173 Ansible automation for the e2e tests
  .github/workflows/consistency-functional.yml
  Makefile
  os_migrate/plugins/module_utils/resource.py
  os_migrate/roles/export_networks/tasks/main.yml
  os_migrate/roles/export_router_interfaces/tasks/main.yml
  os_migrate/roles/export_routers/tasks/main.yml
  os_migrate/roles/export_security_group_rules/tasks/main.yml
  os_migrate/roles/export_security_groups/tasks/main.yml
  os_migrate/roles/export_subnets/tasks/main.yml
  os_migrate/roles/export_workloads/tasks/main.yml
  os_migrate/roles/import_networks/tasks/main.yml
  os_migrate/roles/import_router_interfaces/tasks/main.yml
  os_migrate/roles/import_routers/tasks/main.yml
  os_migrate/roles/import_security_group_rules/tasks/main.yml
  os_migrate/roles/import_security_groups/tasks/main.yml
  os_migrate/roles/import_subnets/tasks/main.yml
  os_migrate/roles/import_workloads/tasks/main.yml
  tests/e2e/ansible.cfg
  tests/e2e/clean.yml
  tests/e2e/prep.yml
  tests/e2e/run.yml
  tests/e2e/seed.yml
  tests/e2e/test_all.yml
Labels: ci, e2e-executed, e2e-run, enhancement
