Repository os-migrate/os-migrate, pull requests merged in 2020-02, with the labels that each got.

#45 Split documentation between developer and user parts
  README.md
  doc/devel/README.md
  doc/devel/design.md
  doc/devel/dev-env-setup.md
  doc/devel/dev-env-vagrant-non-containerized.md
  doc/user/README.md
Labels: documentation

#59 Allow exporting non-uniquely named resource sets
  os_migrate/plugins/filter/stringfilter.py
  os_migrate/plugins/module_utils/network.py
  os_migrate/plugins/module_utils/serialization.py
  os_migrate/plugins/modules/export_network.py
  os_migrate/roles/export_networks/tasks/main.yml
  os_migrate/tests/unit/fixtures.py
  os_migrate/tests/unit/test_filesystem.py
  os_migrate/tests/unit/test_network.py
  os_migrate/tests/unit/test_serialization.py
  os_migrate/tests/unit/test_stringfilter.py
Labels: WIP, idea

#86 Update Vagrant-Devstack setup to Fedora 30
  toolbox/vagrant/ansible/roles/devstack/tasks/config.yml
  toolbox/vagrant/vagrant-config.yml
  toolbox/vagrant/vagrant-up
Labels: dev env

#87 Including matching id by name for the security group name on rules param section
  os_migrate/plugins/module_utils/network.py
  os_migrate/plugins/module_utils/reference.py
  os_migrate/plugins/modules/export_security_group_rules.py
  os_migrate/tests/unit/fixtures.py
  os_migrate/tests/unit/test_security_group_rule.py
Labels: tech debt

#84 Add validation of unique resource naming
  os_migrate/playbooks/validate_data_dir.yml
  os_migrate/plugins/module_utils/validation.py
  os_migrate/plugins/modules/validate_resource_files.py
  os_migrate/roles/import_networks/defaults/main.yml
  os_migrate/roles/import_networks/tasks/main.yml
  os_migrate/roles/validate_data_dir/tasks/main.yml
  os_migrate/tests/unit/test_validation.py
  tests/func/data/validate_data_dir/invalid/networks-duplicate.yml
  tests/func/data/validate_data_dir/invalid/networks.yml
  tests/func/data/validate_data_dir/valid/networks.yml
  tests/func/independent/all.yml
  tests/func/independent/validate_data_dir.yml
  tests/func/test_all.yml
Labels: enhancement

#68 Correct $HOME ownership in vagrant-run and vagrant-shell
  toolbox/vagrant-run
Labels: dev env

#91 Include functional tests from exporting security groups and security group rules
  os_migrate/plugins/modules/export_security_group.py
  os_migrate/plugins/modules/export_security_group_rules.py
  tests/func/clean/all.yml
  tests/func/clean/security_group.yml
  tests/func/clean/security_group_rule.yml
  tests/func/run/all.yml
  tests/func/run/security_group.yml
  tests/func/run/security_group_rule.yml
  tests/func/seed/all.yml
  tests/func/seed/security_group.yml
  tests/func/seed/security_group_rule.yml
Labels: tech debt
