Repository os-migrate/os-migrate, pull requests merged in 2020-11, with the labels that each got.

#298 Take info about server ports from Neutron
  os_migrate/plugins/module_utils/const.py
  os_migrate/plugins/module_utils/exc.py
  os_migrate/plugins/module_utils/server.py
  os_migrate/plugins/module_utils/server_port.py
  os_migrate/tests/unit/test_server.py
  os_migrate/tests/unit/test_server_port.py
  tests/e2e/test_as_tenant.yml
Labels: enhancement

#313 Dev: allow building docs locally
  Makefile
  docs/src/.gitignore
  docs/src/changelog.rst
  scripts/build.sh
  scripts/docs-build.sh
  toolbox/build/venv-requirements.txt
Labels: dev env, documentation, enhancement

#315 Dev: Same wording on landing page as in official docs
  os_migrate/README.md
Labels: documentation

#314 Docs for docs contributions, developer docs polishing
  docs/src/devel/README.rst
  docs/src/devel/contributing-code.rst
  docs/src/devel/contributing-docs.rst
  docs/src/devel/contributing-general.rst
  docs/src/devel/design.rst
  docs/src/devel/dev-env-setup.rst
  docs/src/devel/dev-env-vagrant-non-containerized.rst
Labels: documentation

#316 Dev: Include role documentation in sphinx template
  docs/src/_exts/ansible-autodoc.py
  docs/src/roles/role-import_security_group_rules.rst
  toolbox/build/venv-requirements.txt
Labels: documentation

#302 New: Floating IP export for servers
  os_migrate/plugins/module_utils/const.py
  os_migrate/plugins/module_utils/server.py
  os_migrate/plugins/module_utils/server_floating_ip.py
  os_migrate/tests/unit/test_server.py
  os_migrate/tests/unit/test_server_floating_ip.py
Labels: enhancement

#318 Fix functional CI by pinning pip version
  .github/workflows/consistency-functional.yml
Labels: blocker, ci
