Repository os-migrate/os-migrate, pull requests merged in 2020-03, with the labels that each got.

#103 Implement Router export
  os_migrate/playbooks/export_routers.yml
  os_migrate/plugins/module_utils/const.py
  os_migrate/plugins/module_utils/reference.py
  os_migrate/plugins/module_utils/router.py
  os_migrate/plugins/modules/export_router.py
  os_migrate/plugins/modules/os_routers_info.py
  os_migrate/roles/export_routers/defaults/main.yml
  os_migrate/roles/export_routers/tasks/main.yml
  os_migrate/tests/unit/fixtures.py
  os_migrate/tests/unit/test_router.py
  tests/func/clean/all.yml
  tests/func/clean/router.yml
  tests/func/run/all.yml
  tests/func/run/router.yml
  tests/func/seed/all.yml
  tests/func/seed/router.yml
Labels: enhancement

#102 Fix podman's TTY-related options in vagrant-run
  toolbox/vagrant-run
Labels: bug, dev env

#109 Fix bashate
  scripts/linters.sh
  scripts/publish.sh
Labels: ci, enhancement

#107 Resource class
  os_migrate/plugins/module_utils/filesystem.py
  os_migrate/plugins/module_utils/network.py
  os_migrate/plugins/module_utils/resource.py
  os_migrate/plugins/module_utils/serialization.py
  os_migrate/plugins/modules/export_network.py
  os_migrate/plugins/modules/import_network.py
  os_migrate/tests/unit/fixtures.py
  os_migrate/tests/unit/test_network.py
  os_migrate/tests/unit/test_resource.py
Labels: refactoring

#111 Python lint checks
  os_migrate/plugins/module_utils/filesystem.py
  os_migrate/plugins/module_utils/network.py
  os_migrate/plugins/module_utils/router.py
  os_migrate/plugins/module_utils/subnet.py
  os_migrate/plugins/module_utils/validation.py
  os_migrate/plugins/modules/export_network.py
  os_migrate/plugins/modules/export_router.py
  os_migrate/plugins/modules/export_security_group.py
  os_migrate/plugins/modules/export_security_group_rules.py
  os_migrate/plugins/modules/read_resources.py
  os_migrate/plugins/modules/validate_resource_files.py
  os_migrate/tests/unit/fixtures.py
  os_migrate/tests/unit/test_resource.py
  os_migrate/tests/unit/test_router.py
  os_migrate/tests/unit/test_stringfilter.py
  scripts/linters.sh
Labels: ci, enhancement

#115 Default implementation for Resource.create_or_update
  os_migrate/plugins/module_utils/network.py
  os_migrate/plugins/module_utils/resource.py
  os_migrate/tests/unit/test_resource.py
Labels: refactoring

#120 Subnets Refactor
  os_migrate/plugins/module_utils/subnet.py
  os_migrate/plugins/modules/export_subnet.py
  os_migrate/tests/unit/test_subnet.py
Labels: refactoring

#118 Refactor router export via Resource subclass
  os_migrate/plugins/module_utils/router.py
  os_migrate/plugins/modules/export_router.py
  os_migrate/tests/unit/fixtures.py
  os_migrate/tests/unit/test_router.py
Labels: refactoring

#127 Start the container MySQL service
  .github/workflows/consistency-functional.yml
  scripts/linters.sh
Labels: bug, ci, tech debt

#130 Use MySQL service
  .github/workflows/consistency-functional.yml
Labels: ci, discussion, enhancement, tech debt

#123 Router Interfaces
  os_migrate/playbooks/export_router_interfaces.yml
  os_migrate/playbooks/import_router_interfaces.yml
  os_migrate/plugins/module_utils/const.py
  os_migrate/plugins/module_utils/exc.py
  os_migrate/plugins/module_utils/reference.py
  os_migrate/plugins/module_utils/resource.py
  os_migrate/plugins/module_utils/router.py
  os_migrate/plugins/module_utils/router_interface.py
  os_migrate/plugins/modules/export_router_interfaces.py
  os_migrate/plugins/modules/import_router_interface.py
  os_migrate/roles/export_router_interfaces/tasks/main.yml
  os_migrate/roles/import_router_interfaces/defaults/main.yml
  os_migrate/roles/import_router_interfaces/tasks/main.yml
  os_migrate/tests/unit/test_router_interface.py
  tests/func/clean/router.yml
  tests/func/clean/subnet.yml
  tests/func/run/all.yml
  tests/func/run/router_interface.yml
  tests/func/seed/router.yml
  tests/func/seed/subnet.yml
Labels: enhancement

#138 Split security groups and rules from networks
  os_migrate/plugins/module_utils/network.py
  os_migrate/plugins/module_utils/security_group.py
  os_migrate/plugins/module_utils/security_group_rule.py
  os_migrate/plugins/modules/export_security_group.py
  os_migrate/plugins/modules/export_security_group_rules.py
  os_migrate/plugins/modules/import_security_group.py
  os_migrate/plugins/modules/import_security_group_rule.py
  os_migrate/tests/unit/test_security_group.py
  os_migrate/tests/unit/test_security_group_rule.py
Labels: enhancement, refactoring

#146 OOP sec group
  os_migrate/plugins/module_utils/security_group.py
  os_migrate/plugins/modules/export_security_group.py
  os_migrate/plugins/modules/import_security_group.py
  os_migrate/tests/unit/fixtures.py
  os_migrate/tests/unit/test_security_group.py
Labels: enhancement, refactoring

#149 Fix subnet import idempotence
  os_migrate/plugins/module_utils/resource.py
  os_migrate/plugins/module_utils/subnet.py
  os_migrate/tests/unit/test_subnet.py
Labels: blocker, bug, ci
