Repository os-migrate/os-migrate, pull requests merged in 2020-05, with the labels that each got.

#180 Allow better workload debug logging and progress tracking
  os_migrate/plugins/module_utils/workload_common.py
  os_migrate/plugins/modules/import_workload.py
  os_migrate/plugins/modules/import_workload_prelim.py
  os_migrate/roles/import_workloads/tasks/main.yml
  os_migrate/roles/import_workloads/tasks/workload.yml
  os_migrate/tests/sanity/ignore-2.9.txt
Labels: e2e-executed, e2e-run, enhancement

#176 Adds test for Router Interface idempotence
  os_migrate/plugins/module_utils/router_interface.py
  tests/func/idempotence/all.yml
  tests/func/idempotence/router_interface.yml
Labels: WIP, e2e-run

#188 Include network mappings in wrapper input.
  os_migrate/plugins/module_utils/server.py
  os_migrate/plugins/modules/import_workload_prelim.py
  os_migrate/tests/unit/test_workload.py
Labels: blocker, bug, ci, enhancement

#187 Project filters for workload import
  os_migrate/plugins/modules/import_workload_prelim.py
  os_migrate/roles/import_workloads/meta/main.yml
  os_migrate/roles/import_workloads/tasks/main.yml
  os_migrate/roles/import_workloads/tasks/workload.yml
Labels: bug, enhancement

#181 Include the workload migration into e2e jobs
  Makefile
  os_migrate/plugins/modules/import_workload.py
  os_migrate/plugins/modules/import_workload_prelim.py
  os_migrate/plugins/modules/os_conversion_host_info.py
  os_migrate/roles/import_workloads/tasks/main.yml
  os_migrate/roles/import_workloads/tasks/workload.yml
  tests/e2e/clean.yml
  tests/e2e/run.yml
  tests/e2e/seed.yml
  toolbox/build/build.sh
Labels: ci, e2e-executed, e2e-run

#191 Reintroduce project filtering into workload migration idempotence check
  os_migrate/plugins/modules/import_workload_prelim.py
Labels: e2e-executed
