Repository os-migrate/os-migrate, pull requests merged in 2020-06, with the labels that each got.

#192 Prepare the release of 0.3.0
  os_migrate/galaxy.yml
  os_migrate/plugins/module_utils/const.py
  tests/func/data/validate_data_dir/invalid/networks-duplicate.yml
  tests/func/data/validate_data_dir/invalid/networks.yml
  tests/func/data/validate_data_dir/valid/networks.yml
Labels: e2e-executed

#202 Fix exporting router interfaces when router name filter is undefined
  os_migrate/roles/export_router_interfaces/defaults/main.yml
Labels: bug

#203 [stable/0.3] Fix exporting router interfaces when router name filter is undefined
  os_migrate/roles/export_router_interfaces/defaults/main.yml
Labels: backport

#209 Fix workload migration pt.1
  Makefile
  os_migrate/localhost_inventory.yml
  os_migrate/plugins/module_utils/server.py
  os_migrate/plugins/modules/export_workload.py
  os_migrate/plugins/modules/import_workload_export_volumes.py
  os_migrate/tests/unit/test_workload.py
  tests/e2e/seed.yml
Labels: bug, ci

#211 Conversion host authorization and use the deploy/delete playbooks in CI
  Makefile
  os_migrate/playbooks/deploy_conversion_hosts.yml
  os_migrate/roles/conversion_host/defaults/main.yml
  os_migrate/roles/conversion_host/tasks/conv_host_inventory.yml
  os_migrate/roles/conversion_host/tasks/link_insert_authorized_key.yml
  os_migrate/roles/conversion_host/tasks/link_insert_private_key.yml
  os_migrate/roles/conversion_host/tasks/link_prepare.yml
  os_migrate/roles/conversion_host/tasks/main.yml
  tests/e2e/clean.yml
  tests/e2e/seed.yml
  tests/e2e/test_all.yml
Labels: enhancement

#212 Adjust playbooks variables
  Makefile
  os_migrate/playbooks/deploy_conversion_hosts.yml
  os_migrate/plugins/modules/import_workload_cleanup.py
  os_migrate/plugins/modules/import_workload_create_instance.py
  os_migrate/plugins/modules/import_workload_export_volumes.py
  os_migrate/plugins/modules/import_workload_transfer_volumes.py
  os_migrate/roles/conversion_host/tasks/link_prepare.yml
  os_migrate/roles/import_workloads/defaults/main.yml
  os_migrate/roles/import_workloads/tasks/main.yml
  os_migrate/roles/import_workloads/tasks/workload.yml
  tests/e2e/run.yml
  tests/e2e/scenario_variables.yml
  tests/e2e/seed.yml
Labels: ci, enhancement

#217 Fix subnet update test
  tests/func/update/network.yml
  tests/func/update/router.yml
  tests/func/update/security_group.yml
  tests/func/update/subnet.yml
Labels: bug, ci

#220 Fix deprecated key name
  os_migrate/plugins/module_utils/server.py
Labels: bug
