Repository os-migrate/os-migrate, pull requests merged in 2021-01, with the labels that each got.

#333 Dev: Fix changelog generation in 'make docs'
  .gitignore
  scripts/docs-build.sh
Labels: documentation

#331 Dev: Mention package dependencies in installation doc
  docs/src/user/install-from-galaxy.rst
Labels: documentation

#332 Dev: use 'make docs' to generate docs in Github Actions
  .github/workflows/docs-build-pr.yml
  .github/workflows/docs-build.yml
  Makefile
Labels: documentation

#327 New: Creation of Floating IPs on migrated workloads
  os_migrate/plugins/module_utils/exc.py
  os_migrate/plugins/module_utils/server.py
  os_migrate/plugins/module_utils/server_floating_ip.py
  os_migrate/tests/unit/test_server_floating_ip.py
  tests/e2e/tenant/run_pre_workload.yml
Labels: enhancement

#301 New: Adds Logic to Unsubscribe RHEL Conversion Hosts
  os_migrate/playbooks/delete_conversion_hosts.yml
  os_migrate/roles/conversion_host/tasks/conv_host_inventory.yml
  os_migrate/roles/conversion_host/tasks/unregister.yml
  tests/e2e/test_as_tenant.yml
Labels: enhancement

#320 Dev: Revert "Fix functional CI by pinning pip version"
  .github/workflows/consistency-functional.yml
Labels: ci

#336 Chg: Pass through all RHSM parameters for conversion hosts
  os_migrate/roles/conversion_host_content/defaults/main.yml
  os_migrate/roles/conversion_host_content/tasks/rhel.yml
Labels: enhancement

#348 Fix: Do not look up server image when boot_disk_copy: true
  os_migrate/plugins/module_utils/server.py
Labels: bug

#349 Fix: Fix image lookup for images owned by tenant
  os_migrate/plugins/module_utils/reference.py
  tests/e2e/tenant/seed_workload.yml
  tests/e2e/test_as_tenant.yml
Labels: bug

#356 Fix: Always stop on errors in conversion host deployment
  os_migrate/playbooks/deploy_conversion_hosts.yml
Labels: bug

#354 Fix: Loosen OpenStack operation timeouts in workload migration
  os_migrate/plugins/module_utils/workload_common.py
Labels: bug
